name: Deploy static site to droplet

on:
  push:
    branches: ["main"]

env:
  REMOTE_PATH: /srv/sites/bsbtracker/public/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Ensure remote directory exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            mkdir -p ${{ env.REMOTE_PATH }}

      # Rsync the built files → droplet (fast, incremental, cleans removed files)
      - name: Rsync build → droplet
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -az --delete
          path: ./dist/
          remote_path: ${{ env.REMOTE_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
